title: Impact of Covid-19 in Colombia
description: Development and evaluation of mathematical and epidemiological models that support decision-making in response to the Covid-19 emergency in Colombia
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
